"""create admins table

Revision ID: 54fa334f6f0b
Revises: 8c2b1fe346dd
Create Date: 2026-08-06 16:37:12.770098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '54fa334f6f0b'
down_revision: Union[str, Sequence[str], None] = '8c2b1fe346dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("admins",
                    sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
                    sa.Column("fullname", sa.String(), nullable=False),
                    sa.Column("email", sa.String(), unique=True, nullable=False),
                    sa.Column("hashed_password", sa.String(), nullable=False),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admins")
    # ### end Alembic commands ###
