"""add client order id

Revision ID: 74312b6f114c
Revises: de99b140265a
Create Date: 2026-09-10 18:23:10.971822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74312b6f114c'
down_revision: Union[str, Sequence[str], None] = 'de99b140265a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('orders', sa.Column('client_order_id', sa.String(length=100), nullable=False))
#     op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
#     op.drop_column('orders', 'client_order_id')
#     # ### end Alembic commands ###


def upgrade() -> None:
    # 1. Add the column as nullable first
    op.add_column('orders', sa.Column('client_order_id', sa.String(length=100), nullable=True))

    # 2. Fill existing rows with unique UUIDs
    op.execute("""
        UPDATE orders
        SET client_order_id = gen_random_uuid()::text
        WHERE client_order_id IS NULL
    """)

    # 3. Make it NOT NULL + unique
    op.alter_column('orders', 'client_order_id',
                    existing_type=sa.String(length=100),
                    nullable=False)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)


def downgrade() -> None:
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_column('orders', 'client_order_id')