"""update product model

Revision ID: 8c2b1fe346dd
Revises: 
Create Date: 2026-08-05 17:15:19.940365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2b1fe346dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###

    # Give exiting products sensible values
    op.execute("UPDATE products SET brand = 'Mimi Luxe' WHERE brand IS NULL")
    op.execute("UPDATE products SET stock_quantity = 0 WHERE stock_quantity IS NULL")
    op.execute("UPDATE products SET is_available = true WHERE is_available IS NULL")

    # Now that existing rows have values,
    # make these fields important.
    op.alter_column('products', 'brand', existing_type=sa.String(), nullable=False)
    op.alter_column('products', 'stock_quantity', existing_type=sa.Integer(), nullable=False)
    op.alter_column('products', 'is_available', existing_type=sa.Boolean(), nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'is_available')
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'description')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
