"""add admin notification settings

Revision ID: de99b140265a
Revises: 90fe911e9d29
Create Date: 2026-09-05 18:51:14.785698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de99b140265a'
down_revision: Union[str, Sequence[str], None] = '90fe911e9d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('admin_notification_email', sa.String(length=255), nullable=True))
    op.add_column('store_settings', sa.Column('admin_notification_phone', sa.String(length=50), nullable=True))
    op.alter_column('store_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('store_settings', 'admin_notification_phone')
    op.drop_column('store_settings', 'admin_notification_email')
    # ### end Alembic commands ###
